<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.EShop_SQL.Application\CA.EShop_SQL.Application.csproj" />
    <ProjectReference Include="..\CA.EShop_SQL.Domain\CA.EShop_SQL.Domain.csproj" />
  </ItemGroup>

</Project>
