// <auto-generated />
using System;
using CA.EShop_SQL.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CA.EShop_SQL.Presistence.Migrations
{
    [DbContext(typeof(CA_AppDbContext))]
    partial class CA_AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CA.EShop_SQL.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("C_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("C_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("DbS_Customers");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.LineItem", b =>
                {
                    b.Property<Guid>("LI_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProdId")
                        .HasColumnType("uuid");

                    b.HasKey("LI_Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProdId");

                    b.ToTable("DbS_LineItems");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("O_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("C_Id")
                        .HasColumnType("uuid");

                    b.HasKey("O_Id");

                    b.HasIndex("C_Id");

                    b.ToTable("DbS_Orders");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.ROSummary", b =>
                {
                    b.Property<Guid>("ROSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Cust_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ROSummaryId");

                    b.ToTable("DbS_ROSummaries");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DbS_Products");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.LineItem", b =>
                {
                    b.HasOne("CA.EShop_SQL.Domain.Orders.Order", null)
                        .WithMany("ROL_I_LineItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("CA.EShop_SQL.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProdId");

                    b.OwnsOne("CA.EShop_SQL.Domain.Products.RMoney", "Price", b1 =>
                        {
                            b1.Property<Guid>("LineItemLI_Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .HasColumnType("text");

                            b1.HasKey("LineItemLI_Id");

                            b1.ToTable("DbS_LineItems");

                            b1.WithOwner()
                                .HasForeignKey("LineItemLI_Id");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.Order", b =>
                {
                    b.HasOne("CA.EShop_SQL.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("C_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Products.Product", b =>
                {
                    b.OwnsOne("CA.EShop_SQL.Domain.Products.RMoney", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("ProductId");

                            b1.ToTable("DbS_Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("CA.EShop_SQL.Domain.Orders.Order", b =>
                {
                    b.Navigation("ROL_I_LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
